inline some out variables
microsoft/OpenAPI.NET pull request #1372
Opened 2023-10-02 08:50 UTC by SimonCropp

2023-10-02 13:54 UTC, baywet requested changes

2023-10-02 13:54 UTC, baywet commented on src/Microsoft.OpenApi.Readers/ParseNodes/PropertyNode.cs
> +            var found = fixedFields.TryGetValue(Name, out var fixedFieldMap);
found is being assigned but never read, maybe this statement could be collapsed into the if condition

2023-10-03 12:52 UTC, baywet submitted a review, later dismissed

2023-10-03 12:52 UTC, baywet commented
@simoncropp this one is conflicting again, would you mind rebasing another time please?

2023-10-03 19:33 UTC, SimonCropp commented
@baywet done

2023-10-03 21:25 UTC, baywet approved these changes

2023-10-03 21:29 UTC, merged